services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_frankenphp
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --host=0.0.0.0 --port=9000
    ports:
      - "9000:9000" # Map port 9000 di laptop ke port 9000 di container
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
